@ECHO OFF

pushd %~dp0

REM Command file for Sphinx documentation

if "%SPHINXBUILD%" == "" (
	set SPHINXBUILD=sphinx-build
)
set SOURCEDIR=source
set BUILDDIR=build
set SPHINXPROJ=lifelib

if "%1" == "" goto help

%SPHINXBUILD% >NUL 2>NUL
if errorlevel 9009 (
	echo.
	echo.The 'sphinx-build' command was not found. Make sure you have Sphinx
	echo.installed, then set the SPHINXBUILD environment variable to point
	echo.to the full path of the 'sphinx-build' executable. Alternatively you
	echo.may add the Sphinx directory to PATH.
	echo.
	echo.If you don't have Sphinx installed, grab it from
	echo.http://sphinx-doc.org/
	exit /b 1
)

REM Update and copy jupyter notebooks for building as static pages
if "%1" == "html" (
	python procnb.py
)

%SPHINXBUILD% -M %1 %SOURCEDIR% %BUILDDIR% %SPHINXOPTS%

if "%1" == "clean" goto remove_dirs
goto end

:help
%SPHINXBUILD% -M help %SOURCEDIR% %BUILDDIR% %SPHINXOPTS%
goto end

:remove_dirs
rmdir /s /q "%SOURCEDIR%\projects\generated"    &:: Auto-generated by autogen
rmdir /s /q "%SOURCEDIR%\modules"               &:: Auto-generated by Sphinx-gallery
rmdir /s /q "%SOURCEDIR%\generated_examples"    &:: Auto-generated by Sphinx-gallery
goto end

:end
popd
